
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export NVM_DIR="/home/frazer/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export EDITOR=/usr/bin/vim
export VISUAL=/usr/bin/vim

export PATH="/usr/local/bin:/usr/local/sbin:~/bin:$PATH"
export PATH="/Users/frazer/.llvm/bin:$PATH"
export LLVM_DIR=/tmp/$USER/build

export JAVA_HOME=$(/usr/libexec/java_home)

# Disable autocorrect
unsetopt correct
unsetopt correct_all

# Add TheFuck alias
eval "$(thefuck --alias)"

# aliases for generating random streams
alias spew='cat /dev/urandom | env LC_CTYPE=C tr -dc '\''[:print:]'\'' | env LC_CTYPE=C tr -d '\''['\''\'\'''\''"`$\\ ]'\'''
alias spewan='cat /dev/urandom | env LC_CTYPE=C tr -dc '\''[:alnum:]'\'''
alias spewlan='cat /dev/urandom | env LC_CTYPE=C tr -dc '\''a-z0-9'\'''
alias genid='spewlan | fold -w 24 | head -n1 | tr -d '\''\n'\'' | pbcopy'
alias genpass='spew | fold -w 64 | head -n1 | tr -d '\''\n'\'' | pbcopy'

alias ls='ls -lhG '
alias lsl='command ls -G '

alias gd='git diff'
alias gdt='git difftool'
alias gdh='git diff HEAD~ HEAD'
alias gST='git status'
alias gst='git status'
alias gcof="gco --"

function gcmp {
  gcm "$@" && git push
}

function gmo {
  git fetch && git merge origin/master
}
function gmop {
  gmo && gti push
}

alias rm='command rm'

export PATH=$PATH:~/code/SDK/air_current/bin:~/code/SDK/android-current/ndk-bundle:~/code/SDK/android-current/platform-tools:/Users/frazer/.miniconda/bin
export ANDROID_HOME=~/Library/Android/sdk
